### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by lylyjy** [angmavrogiannis/B-GAP-Behavior-Guided-Action-Prediction-and-Navigation-for-Autonomous-Driving#1]
Traceback (most recent call last):
  File "experiments.py", line 152, in <module>
    main()
  File "experiments.py", line 45, in main
    evaluate(opts['<environment>'], opts['<agent>'], opts)
  File "experiments.py", line 64, in evaluate
    agent = load_agent(agent_config, env)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python37\site-packages\rl_agents\agents\common\factory.py", line 41, in load_agent
    return agent_factory(env, agent_config)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python37\site-packages\rl_agents\agents\common\factory.py", line 24, in agent_factory
    agent = agent_class(environment, config)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python37\site-packages\rl_agents\agents\deep_q_network\pytorch.py", line 18, in __init__
    self.value_net = model_factory(self.config["model"])
  File "C:\Users\lenovo\AppData\Roaming\Python\Python37\site-packages\rl_agents\agents\common\models.py", line 441, in model_factory
    raise ValueError("Unknown model type")
ValueError: Unknown model type

**Comment by zhangfengyo** [comment]
i have meet the same problem

**Comment by kaustabpal** [comment]
I am facing the same problem. 

Command: 
```python
python experiments.py evaluate configs/HighwayEnv/env.json configs/HighwayEnv/agents/DQNAgent/gcn.json --test --episodes=10 --name-from-config --recover-from=/rl-agents/scripts/out/HighwayEnv/DQNAgent/saved_models/
```
Output:
```
INFO: Making new env: highway-v0
Traceback (most recent call last):
  File "experiments.py", line 152, in <module>
    main()
  File "experiments.py", line 45, in main
    evaluate(opts['<environment>'], opts['<agent>'], opts)
  File "experiments.py", line 64, in evaluate
    agent = load_agent(agent_config, env)
  File "/Users/kaustabpal/.local/lib/python3.8/site-packages/rl_agents/agents/common/factory.py", line 41, in load_agent
    return agent_factory(env, agent_config)
  File "/Users/kaustabpal/.local/lib/python3.8/site-packages/rl_agents/agents/common/factory.py", line 24, in agent_factory
    agent = agent_class(environment, config)
  File "/Users/kaustabpal/.local/lib/python3.8/site-packages/rl_agents/agents/deep_q_network/pytorch.py", line 18, in __init__
    self.value_net = model_factory(self.config["model"])
  File "/Users/kaustabpal/.local/lib/python3.8/site-packages/rl_agents/agents/common/models.py", line 441, in model_factory
    raise ValueError("Unknown model type")
ValueError: Unknown model type
```

**Comment by angmavrogiannis** [comment]
Hello, this is a previous version of the paper. Since then, we have resubmitted and removed the graph neural network, only retaining the MLP. It looks like there is some sort of incompatibility because of the graph network that the latest version does not use. I will update the repo to the current version which only uses MLP and will close the issue once it's resolved.

**Comment by angmavrogiannis** [comment]
As I just mentioned in the other issue and also closed it, I have removed the GCN functionality, so you can only train a DQN agent for now. I just updated the repo to be compatible with latest version of highway-env. You can train a DQN agent for 10 episodes from the rl-agents/scripts directory with the following command:

python experiments.py evaluate configs/HighwayEnv/env.json configs/HighwayEnv/agents/DQNAgent/dqn.json --train --episodes=10 --name-from-config

I am soon going to update the instructions in the repo, as in how you can choose how many aggressive/conservative cars you can add to the environment etc. but for now, you can check the highway_env.py file and modify the parameters in the default_config function to run different experiments. I can also add the GCN implementation, but the current implementation is not providing good training/test results.

Let me know if you have any other questions.

Angelos
